// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// OptimizeMICL
S4 OptimizeMICL(S4 obj, int optimize);
RcppExport SEXP VarSelLCM_OptimizeMICL(SEXP objSEXP, SEXP optimizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type obj(objSEXP);
    Rcpp::traits::input_parameter< int >::type optimize(optimizeSEXP);
    __result = Rcpp::wrap(OptimizeMICL(obj, optimize));
    return __result;
END_RCPP
}
